{
  nodes(filter: {
    created: {
      after: "2018-03-01",
      before: "2018-03-03"
    }
  }) {
    name
  }
  notNodes:nodes(filter: {
    not: {
      created: {
        after: "2018-03-01",
        before: "2018-03-03"
      }
    }
  }) {
    name
  }
}
