{
  nodes(filter: {
    created: {
      and: [
        {after: "2018-03-04T00:00:00Z"},
        {after: "2018-03-04T00:30:00"},
        {after: "2018-03-04"},
        {after: "2018-03-04T00:30:00+02:00"}
        {after: "2018-03-04T00:30:00+02:00[Europe/Vienna]"}
      ]
    }
  }) {
    name
  }
}
